[package]
name = "asteroid-mq"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bytes = {version = "1.6.1", features = ["serde"]}
chrono = "0.4.38"
crossbeam = "0.8.4"
dashmap = "6.0.1"
flume = "0.11.0"
futures-util = {version = "0.3.30", features = ["sink"]}
machine-uid = "0.5.2"
pin-project-lite = "0.2.14"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio = { version = "1.39.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
